export { default as Nav } from './Nav'
export { default as Footer } from './Footer'
export { default as About } from './About'
export { default as Checkout } from './Checkout'
export { default as Features } from './Features'